import React from 'react'
import Head from 'next/head'
const Meta = () => {
  return (
    <Head>
      <title>Weather - Next App</title>
      <meta name="description" content="It was Generated By Next JS App" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default Meta
