import React, { useState } from "react";
import Head from "next/head";
import { BsSearch } from "react-icons/bs";
import axios from "axios";

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");



  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");

    axios
      .get(url)
      .then((response) => {
        setWeather(response.data);
        console.log(response.data);
      })
      .catch((error) => {
        setError("Error fetching weather data. Please try again.");
        console.log(error);
      })
      .finally(() => {
        setLoading(false);
        setCity("");
      });
  };

  return (
    <div>
      <Head>
        <title>Weather - Next App</title>
        <meta name="description" content="It was Generated By Next JS App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form onSubmit={fetchWeather}>
        <input
          type="text"
          value={city}
          onChange={(e) => setCity(e.target.value)}
          placeholder="Enter city name"
        />
        <button
          type="submit"
          className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
          disabled={loading}
        >
          {loading ? "Loading..." : "Fetch weather"}
        </button>
      </form>
      {error && <p>{error}</p>}
    </div>
  );
}
